baseURL = "https://huge.python.army/"
defaultContentLanguage = "en"
languageCode = "en"
title = "Huge Pythons"
theme = "LoveIt"

[Params]
    # LoveIt theme version. Set it carefully.
    version = "0.1.X"

    intro = true
    headline = "You know our pythons"
    description = "No Sean available."
    github = "https://github.com/buddisattva/huge-python"
    twitter = "https://twitter.com/realdonaldtrump"
    email = "musian@python.army"
    opengraph = true
    shareTwitter = true
    dateFormat = "Fri, Mar 13, 2020"

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is allowed), such as icons
    pre = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3